// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RailwayProject.Models;

#nullable disable

namespace RailwayProject.Migrations
{
    [DbContext(typeof(RailwayDBContext))]
    [Migration("20231125143251_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RailwayProject.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoOfCompartment")
                        .HasColumnType("int");

                    b.Property<int>("NoOfSeat")
                        .HasColumnType("int");

                    b.Property<int>("SeatAvailable")
                        .HasColumnType("int");

                    b.Property<string>("TrainCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TrainCode");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Personal cabin(4)or coupe(2seat)\nPrivacy\nHigh fare\nComfortable Seat\nU can carry your Dog",
                            Name = "Class S",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 8,
                            TrainCode = "SE101",
                            TypeCode = "AC1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Personal cabin(4)or coupe(2seat)\nPrivacy\nHigh fare\nComfortable Seat\nU can carry your Dog",
                            Name = "Class S",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 2,
                            TrainCode = "SE101",
                            TypeCode = "AC1"
                        },
                        new
                        {
                            Id = 3,
                            Description = "No privacy\nComparatively Comfortable\nAverage fare\nNo dogs allowed\nluggage spaceious",
                            Name = "Class A",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 4,
                            TrainCode = "SE101",
                            TypeCode = "AC2"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Average Rush\nCooling worth comfort\nLess Lagague space\nAgain No Dogs",
                            Name = "Class B",
                            NoOfCompartment = 6,
                            NoOfSeat = 2,
                            SeatAvailable = 12,
                            TrainCode = "SE101",
                            TypeCode = "AC3"
                        },
                        new
                        {
                            Id = 5,
                            Description = "more comfor and amenities\nhigher fare",
                            Name = "Class C",
                            NoOfCompartment = 6,
                            NoOfSeat = 6,
                            SeatAvailable = 20,
                            TrainCode = "SE101",
                            TypeCode = "SL"
                        },
                        new
                        {
                            Id = 6,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 64,
                            TrainCode = "SE101",
                            TypeCode = "GE"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Personal cabin(4)or coupe(2seat)\nPrivacy\nHigh fare\nComfortable Seat\nU can carry your Dog",
                            Name = "Class S",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 8,
                            TrainCode = "SE201",
                            TypeCode = "AC1"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Personal cabin(4)or coupe(2seat)\nPrivacy\nHigh fare\nComfortable Seat\nU can carry your Dog",
                            Name = "Class S",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 10,
                            TrainCode = "SE201",
                            TypeCode = "AC2"
                        },
                        new
                        {
                            Id = 9,
                            Description = "more comfor and amenities\\nhigher fare",
                            Name = "Class C",
                            NoOfCompartment = 6,
                            NoOfSeat = 6,
                            SeatAvailable = 12,
                            TrainCode = "SE201",
                            TypeCode = "SL"
                        },
                        new
                        {
                            Id = 10,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 3,
                            TrainCode = "SE201",
                            TypeCode = "GE"
                        },
                        new
                        {
                            Id = 11,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 2,
                            TrainCode = "SE201",
                            TypeCode = "GE"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Personal cabin(4)or coupe(2seat)\nPrivacy\nHigh fare\nComfortable Seat\nU can carry your Dog",
                            Name = "Class S",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 8,
                            TrainCode = "SE301",
                            TypeCode = "AC1"
                        },
                        new
                        {
                            Id = 13,
                            Description = "No privacy\nComparatively Comfortable\nAverage fare\nNo dogs allowed\nluggage spaceious",
                            Name = "Class A",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 8,
                            TrainCode = "SE301",
                            TypeCode = "AC2"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Average Rush\nCooling worth comfort\nLess Lagague space\nAgain No Dogs",
                            Name = "Class B",
                            NoOfCompartment = 6,
                            NoOfSeat = 2,
                            SeatAvailable = 12,
                            TrainCode = "SE301",
                            TypeCode = "AC3"
                        },
                        new
                        {
                            Id = 15,
                            Description = "more comfor and amenities\\nhigher fare",
                            Name = "Class C",
                            NoOfCompartment = 6,
                            NoOfSeat = 6,
                            SeatAvailable = 22,
                            TrainCode = "SE301",
                            TypeCode = "SL"
                        },
                        new
                        {
                            Id = 16,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 22,
                            TrainCode = "SE301",
                            TypeCode = "GE"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Personal cabin(4)or coupe(2seat)\nPrivacy\nHigh fare\nComfortable Seat\nU can carry your Dog",
                            Name = "Class S",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 8,
                            TrainCode = "SE401",
                            TypeCode = "AC1"
                        },
                        new
                        {
                            Id = 18,
                            Description = "No privacy\nComparatively Comfortable\nAverage fare\nNo dogs allowed\nluggage spaceious",
                            Name = "Class A",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 8,
                            TrainCode = "SE401",
                            TypeCode = "AC2"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Average Rush\nCooling worth comfort\nLess Lagague space\nAgain No Dogs",
                            Name = "Class B",
                            NoOfCompartment = 6,
                            NoOfSeat = 2,
                            SeatAvailable = 12,
                            TrainCode = "SE401",
                            TypeCode = "AC3"
                        },
                        new
                        {
                            Id = 20,
                            Description = "more comfor and amenities\\nhigher fare",
                            Name = "Class C",
                            NoOfCompartment = 6,
                            NoOfSeat = 6,
                            SeatAvailable = 20,
                            TrainCode = "SE401",
                            TypeCode = "SL"
                        },
                        new
                        {
                            Id = 21,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 24,
                            TrainCode = "SE401",
                            TypeCode = "GE"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Personal cabin(4)or coupe(2seat)\nPrivacy\nHigh fare\nComfortable Seat\nU can carry your Dog",
                            Name = "Class S",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 2,
                            TrainCode = "SE501",
                            TypeCode = "AC1"
                        },
                        new
                        {
                            Id = 23,
                            Description = "No privacy\nComparatively Comfortable\nAverage fare\nNo dogs allowed\nluggage spaceious",
                            Name = "Class A",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 3,
                            TrainCode = "SE501",
                            TypeCode = "AC2"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Average Rush\nCooling worth comfort\nLess Lagague space\nAgain No Dogs",
                            Name = "Class B",
                            NoOfCompartment = 6,
                            NoOfSeat = 2,
                            SeatAvailable = 10,
                            TrainCode = "SE501",
                            TypeCode = "AC3"
                        },
                        new
                        {
                            Id = 25,
                            Description = "more comfor and amenities\\nhigher fare",
                            Name = "Class C",
                            NoOfCompartment = 6,
                            NoOfSeat = 6,
                            SeatAvailable = 17,
                            TrainCode = "SE501",
                            TypeCode = "SL"
                        },
                        new
                        {
                            Id = 26,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 13,
                            TrainCode = "SE501",
                            TypeCode = "GE"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Personal cabin(4)or coupe(2seat)\nPrivacy\nHigh fare\nComfortable Seat\nU can carry your Dog",
                            Name = "Class S",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 7,
                            TrainCode = "SE601",
                            TypeCode = "AC1"
                        },
                        new
                        {
                            Id = 28,
                            Description = "No privacy\nComparatively Comfortable\nAverage fare\nNo dogs allowed\nluggage spaceious",
                            Name = "Class A",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 6,
                            TrainCode = "SE601",
                            TypeCode = "AC2"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Average Rush\nCooling worth comfort\nLess Lagague space\nAgain No Dogs",
                            Name = "Class B",
                            NoOfCompartment = 6,
                            NoOfSeat = 2,
                            SeatAvailable = 10,
                            TrainCode = "SE601",
                            TypeCode = "AC3"
                        },
                        new
                        {
                            Id = 30,
                            Description = "more comfor and amenities\\nhigher fare",
                            Name = "Class C",
                            NoOfCompartment = 6,
                            NoOfSeat = 6,
                            SeatAvailable = 20,
                            TrainCode = "SE601",
                            TypeCode = "SL"
                        },
                        new
                        {
                            Id = 31,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 12,
                            TrainCode = "SE601",
                            TypeCode = "GE"
                        },
                        new
                        {
                            Id = 32,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 13,
                            TrainCode = "SE601",
                            TypeCode = "GE"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Personal cabin(4)or coupe(2seat)\nPrivacy\nHigh fare\nComfortable Seat\nU can carry your Dog",
                            Name = "Class S",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 8,
                            TrainCode = "SE701",
                            TypeCode = "AC1"
                        },
                        new
                        {
                            Id = 34,
                            Description = "No privacy\nComparatively Comfortable\nAverage fare\nNo dogs allowed\nluggage spaceious",
                            Name = "Class A",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 8,
                            TrainCode = "SE701",
                            TypeCode = "AC2"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Average Rush\nCooling worth comfort\nLess Lagague space\nAgain No Dogs",
                            Name = "Class B",
                            NoOfCompartment = 6,
                            NoOfSeat = 2,
                            SeatAvailable = 11,
                            TrainCode = "SE701",
                            TypeCode = "AC3"
                        },
                        new
                        {
                            Id = 36,
                            Description = "more comfor and amenities\\nhigher fare",
                            Name = "Class C",
                            NoOfCompartment = 6,
                            NoOfSeat = 6,
                            SeatAvailable = 22,
                            TrainCode = "SE701",
                            TypeCode = "SL"
                        },
                        new
                        {
                            Id = 37,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 16,
                            TrainCode = "SE701",
                            TypeCode = "GE"
                        },
                        new
                        {
                            Id = 38,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 28,
                            TrainCode = "SE701",
                            TypeCode = "GE"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Personal cabin(4)or coupe(2seat)\nPrivacy\nHigh fare\nComfortable Seat\nU can carry your Dog",
                            Name = "Class S",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 8,
                            TrainCode = "SE801",
                            TypeCode = "AC1"
                        },
                        new
                        {
                            Id = 40,
                            Description = "No privacy\nComparatively Comfortable\nAverage fare\nNo dogs allowed\nluggage spaceious",
                            Name = "Class A",
                            NoOfCompartment = 4,
                            NoOfSeat = 2,
                            SeatAvailable = 8,
                            TrainCode = "SE801",
                            TypeCode = "AC2"
                        },
                        new
                        {
                            Id = 41,
                            Description = "Average Rush\nCooling worth comfort\nLess Lagague space\nAgain No Dogs",
                            Name = "Class B",
                            NoOfCompartment = 6,
                            NoOfSeat = 2,
                            SeatAvailable = 11,
                            TrainCode = "SE801",
                            TypeCode = "AC3"
                        },
                        new
                        {
                            Id = 42,
                            Description = "more comfor and amenities\\nhigher fare",
                            Name = "Class C",
                            NoOfCompartment = 6,
                            NoOfSeat = 6,
                            SeatAvailable = 10,
                            TrainCode = "SE801",
                            TypeCode = "SL"
                        },
                        new
                        {
                            Id = 43,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 16,
                            TrainCode = "SE801",
                            TypeCode = "GE"
                        },
                        new
                        {
                            Id = 44,
                            Description = "basic amenities\nbudget-friendly\nbench-type seats\nmore people",
                            Name = "Class D",
                            NoOfCompartment = 4,
                            NoOfSeat = 16,
                            SeatAvailable = 22,
                            TrainCode = "SE801",
                            TypeCode = "GE"
                        });
                });

            modelBuilder.Entity("RailwayProject.Models.Fare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DistanceRange")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfTrain")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.ToTable("Fares");
                });

            modelBuilder.Entity("RailwayProject.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("EndStationId")
                        .HasColumnType("int");

                    b.Property<int>("StartStationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndStationId");

                    b.HasIndex("StartStationId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Distance = 1726,
                            EndStationId = 4,
                            StartStationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Distance = 1726,
                            EndStationId = 4,
                            StartStationId = 1
                        },
                        new
                        {
                            Id = 3,
                            Distance = 1726,
                            EndStationId = 1,
                            StartStationId = 4
                        },
                        new
                        {
                            Id = 4,
                            Distance = 1726,
                            EndStationId = 1,
                            StartStationId = 4
                        });
                });

            modelBuilder.Entity("RailwayProject.Models.RouteDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrivalStationId")
                        .HasColumnType("int");

                    b.Property<int>("DelayTime")
                        .HasColumnType("int");

                    b.Property<int>("DepartureStationId")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<double>("TravelTime")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalStationId");

                    b.HasIndex("DepartureStationId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalStationId = 2,
                            DelayTime = 13,
                            DepartureStationId = 1,
                            Distance = 411,
                            RouteId = 1,
                            TravelTime = 8.0
                        },
                        new
                        {
                            Id = 2,
                            ArrivalStationId = 3,
                            DelayTime = 13,
                            DepartureStationId = 2,
                            Distance = 627,
                            RouteId = 1,
                            TravelTime = 12.4
                        },
                        new
                        {
                            Id = 3,
                            ArrivalStationId = 4,
                            DelayTime = 12,
                            DepartureStationId = 3,
                            Distance = 688,
                            RouteId = 1,
                            TravelTime = 15.6
                        },
                        new
                        {
                            Id = 4,
                            ArrivalStationId = 3,
                            DelayTime = 10,
                            DepartureStationId = 1,
                            Distance = 1038,
                            RouteId = 2,
                            TravelTime = 21.399999999999999
                        },
                        new
                        {
                            Id = 5,
                            ArrivalStationId = 4,
                            DelayTime = 12,
                            DepartureStationId = 3,
                            Distance = 688,
                            RouteId = 2,
                            TravelTime = 10.6
                        },
                        new
                        {
                            Id = 6,
                            ArrivalStationId = 3,
                            DelayTime = 10,
                            DepartureStationId = 4,
                            Distance = 688,
                            RouteId = 3,
                            TravelTime = 12.6
                        },
                        new
                        {
                            Id = 7,
                            ArrivalStationId = 2,
                            DelayTime = 12,
                            DepartureStationId = 3,
                            Distance = 627,
                            RouteId = 3,
                            TravelTime = 13.6
                        },
                        new
                        {
                            Id = 8,
                            ArrivalStationId = 1,
                            DelayTime = 12,
                            DepartureStationId = 2,
                            Distance = 411,
                            RouteId = 3,
                            TravelTime = 8.5999999999999996
                        },
                        new
                        {
                            Id = 9,
                            ArrivalStationId = 2,
                            DelayTime = 12,
                            DepartureStationId = 4,
                            Distance = 1315,
                            RouteId = 4,
                            TravelTime = 22.600000000000001
                        },
                        new
                        {
                            Id = 10,
                            ArrivalStationId = 1,
                            DelayTime = 12,
                            DepartureStationId = 2,
                            Distance = 411,
                            RouteId = 4,
                            TravelTime = 7.5999999999999996
                        });
                });

            modelBuilder.Entity("RailwayProject.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("RouteId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool>("ScheduleCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartAt")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("TrainCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("TrainCode");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndAt = new DateTime(2023, 11, 27, 19, 12, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 1,
                            ScheduleCompleted = false,
                            StartAt = new DateTime(2023, 11, 26, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainCode = "SE801"
                        },
                        new
                        {
                            Id = 2,
                            EndAt = new DateTime(2023, 11, 28, 2, 30, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 1,
                            ScheduleCompleted = false,
                            StartAt = new DateTime(2023, 11, 26, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainCode = "SE601"
                        },
                        new
                        {
                            Id = 3,
                            EndAt = new DateTime(2023, 11, 28, 7, 10, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 1,
                            ScheduleCompleted = false,
                            StartAt = new DateTime(2023, 11, 26, 19, 20, 0, 0, DateTimeKind.Unspecified),
                            TrainCode = "SE201"
                        },
                        new
                        {
                            Id = 4,
                            EndAt = new DateTime(2023, 11, 27, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 2,
                            ScheduleCompleted = false,
                            StartAt = new DateTime(2023, 11, 26, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TrainCode = "SE401"
                        },
                        new
                        {
                            Id = 5,
                            EndAt = new DateTime(2023, 11, 27, 20, 32, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 3,
                            ScheduleCompleted = false,
                            StartAt = new DateTime(2023, 11, 26, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            TrainCode = "SE701"
                        },
                        new
                        {
                            Id = 6,
                            EndAt = new DateTime(2023, 11, 29, 3, 12, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 3,
                            ScheduleCompleted = false,
                            StartAt = new DateTime(2023, 11, 26, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            TrainCode = "SE501"
                        },
                        new
                        {
                            Id = 7,
                            EndAt = new DateTime(2023, 11, 27, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 3,
                            ScheduleCompleted = false,
                            StartAt = new DateTime(2023, 11, 26, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            TrainCode = "SE101"
                        },
                        new
                        {
                            Id = 8,
                            EndAt = new DateTime(2023, 11, 27, 8, 25, 0, 0, DateTimeKind.Unspecified),
                            RouteId = 4,
                            ScheduleCompleted = false,
                            StartAt = new DateTime(2023, 11, 26, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            TrainCode = "SE301"
                        });
                });

            modelBuilder.Entity("RailwayProject.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NameOfDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZipCode")
                        .HasColumnType("int");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NameOfDivision = "Ho Chi Minh City",
                            StationCode = "SGO",
                            StationName = "Sai Gon",
                            ZipCode = 700000,
                            Zone = "Southern"
                        },
                        new
                        {
                            Id = 2,
                            NameOfDivision = "Khanh Hoa Province",
                            StationCode = "NTR",
                            StationName = "Nha Trang",
                            ZipCode = 650000,
                            Zone = "Central"
                        },
                        new
                        {
                            Id = 3,
                            NameOfDivision = "Thua Thien Hue Province",
                            StationCode = "HUE",
                            StationName = "Hue",
                            ZipCode = 530000,
                            Zone = "Central"
                        },
                        new
                        {
                            Id = 4,
                            NameOfDivision = "Hanoi Capital",
                            StationCode = "HNO",
                            StationName = "Ha Noi",
                            ZipCode = 700000,
                            Zone = "North"
                        });
                });

            modelBuilder.Entity("RailwayProject.Models.Train", b =>
                {
                    b.Property<string>("TrainCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainCode");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            TrainCode = "SE101",
                            Description = "Train SE1 is a fast train running on the North-South unified train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE1",
                            TypeCode = "F"
                        },
                        new
                        {
                            TrainCode = "SE102",
                            Description = "Train SE1 is a fast train running on the North-South unified train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE1",
                            TypeCode = "F"
                        },
                        new
                        {
                            TrainCode = "SE201",
                            Description = "Train SE2 is a fast train running on the unified North-South train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE2",
                            TypeCode = "F"
                        },
                        new
                        {
                            TrainCode = "SE202",
                            Description = "Train SE2 is a fast train running on the unified North-South train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE2",
                            TypeCode = "F"
                        },
                        new
                        {
                            TrainCode = "SE301",
                            Description = "The SE3 train is the fastest and most beautiful train running on the unified North-South train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE3",
                            TypeCode = "SF"
                        },
                        new
                        {
                            TrainCode = "SE302",
                            Description = "The SE3 train is the fastest and most beautiful train running on the unified North-South train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE3",
                            TypeCode = "SF"
                        },
                        new
                        {
                            TrainCode = "SE401",
                            Description = "Train SE4 is the fastest and most beautiful train running on the North-South unified train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE4",
                            TypeCode = "SF"
                        },
                        new
                        {
                            TrainCode = "SE402",
                            Description = "Train SE4 is the fastest and most beautiful train running on the North-South unified train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE4",
                            TypeCode = "SF"
                        },
                        new
                        {
                            TrainCode = "SE501",
                            Description = "Train SE5 is a slow train running on the unified North-South train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE5",
                            TypeCode = "S"
                        },
                        new
                        {
                            TrainCode = "SE502",
                            Description = "Train SE5 is a slow train running on the unified North-South train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE5",
                            TypeCode = "S"
                        },
                        new
                        {
                            TrainCode = "SE601",
                            Description = "Train SE6 is a slow train running on the unified North-South train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE6",
                            TypeCode = "S"
                        },
                        new
                        {
                            TrainCode = "SE602",
                            Description = "Train SE6 is a slow train running on the unified North-South train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE6",
                            TypeCode = "S"
                        },
                        new
                        {
                            TrainCode = "SE701",
                            Description = "Train SE7 is a fast train running on the North-South unified train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE7",
                            TypeCode = "F"
                        },
                        new
                        {
                            TrainCode = "SE702",
                            Description = "Train SE7 is a fast train running on the North-South unified train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE7",
                            TypeCode = "F"
                        },
                        new
                        {
                            TrainCode = "SE801",
                            Description = "Train SE8 is a fast train running on the North-South unified train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE8",
                            TypeCode = "F"
                        },
                        new
                        {
                            TrainCode = "SE802",
                            Description = "Train SE8 is a fast train running on the North-South unified train route. The Railway industry is trying to improve service quality and train speed to increasingly meet the travel needs of customers.",
                            IsRunning = true,
                            Name = "SE8",
                            TypeCode = "F"
                        });
                });

            modelBuilder.Entity("RailwayProject.Models.Class", b =>
                {
                    b.HasOne("RailwayProject.Models.Train", "Trains")
                        .WithMany("Classes")
                        .HasForeignKey("TrainCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trains");
                });

            modelBuilder.Entity("RailwayProject.Models.Fare", b =>
                {
                    b.HasOne("RailwayProject.Models.Route", "Route")
                        .WithMany("Fares")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("RailwayProject.Models.Route", b =>
                {
                    b.HasOne("RailwayProject.Models.Station", "EndStation")
                        .WithMany("EndRoutes")
                        .HasForeignKey("EndStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailwayProject.Models.Station", "StartStation")
                        .WithMany("StartRoutes")
                        .HasForeignKey("StartStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndStation");

                    b.Navigation("StartStation");
                });

            modelBuilder.Entity("RailwayProject.Models.RouteDetail", b =>
                {
                    b.HasOne("RailwayProject.Models.Station", "ArrivalStation")
                        .WithMany("ArrivalRouteDetails")
                        .HasForeignKey("ArrivalStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailwayProject.Models.Station", "DepartureStation")
                        .WithMany("DepartureRouteDetails")
                        .HasForeignKey("DepartureStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailwayProject.Models.Route", "Route")
                        .WithMany("RouteDetails")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrivalStation");

                    b.Navigation("DepartureStation");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("RailwayProject.Models.Schedule", b =>
                {
                    b.HasOne("RailwayProject.Models.Route", "Route")
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RailwayProject.Models.Train", "Train")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("RailwayProject.Models.Route", b =>
                {
                    b.Navigation("Fares");

                    b.Navigation("RouteDetails");
                });

            modelBuilder.Entity("RailwayProject.Models.Station", b =>
                {
                    b.Navigation("ArrivalRouteDetails");

                    b.Navigation("DepartureRouteDetails");

                    b.Navigation("EndRoutes");

                    b.Navigation("StartRoutes");
                });

            modelBuilder.Entity("RailwayProject.Models.Train", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
